### ISSUE TITLE
Command intuitiveness for users

### ISSUE THREAD

**Issue by Chaussettes99** [Chaussettes99/DH-Statsbot#1]
# Problem

The `!map stats` command has consistently been something very confusing and difficult for people to use to the point that it's barely worth having it included in the bot. Issues need to be addressed to make this a function that doesn't make myself and other users tear their hair out when trying to use it correctly.

* Currently, users need to append either "_advance", "_push", or "_clash" onto the map's name to correctly use the command if the map has multiple versions. If there is only 1 version, it's simply the map's name. This is very confusing as you have no way of knowing what maps have multiple versions.

* Users have no way of knowing what maps are included.

* Armored maps aren't included in the current implementation. They need to be included in the eventual rewrite.

### Probable solution(s)
Having users simply write the name of the map is ideal, but the issue of multiple versions of the same map still exists. Without cluttering the channel in the Discord, some type of "selection menu" will have to be done. 

Example: User types `!map stats stoumont`, Stoumont currently has 2 versions: Advance and Push. The bot would simply reply with a selection to choose either with a number or other identifier, IE: `1 - Advance | 2 - Push`. This would make it very easy for the user to select what version of the map they wish to choose.

**Comment by shiftycats** [comment]
Use fuzzy search for looking up map names. Users should be able to provide a "close enough" string, like `!map redeadv` for example, and it should match to `Rederitz Advance`.

Here's a couple libraries to help with that:
* https://github.com/taleinat/fuzzysearch 
* https://github.com/seatgeek/fuzzywuzzy

**Comment by Chaussettes99** [comment]
> 
> 
> Use fuzzy search for looking up map names. Users should be able to provide a "close enough" string, like `!map stats redeadv` for example, and it should match to `Rederitz Advance`.
> 
> Here's a couple libraries to help with that:
> 
>     * https://github.com/taleinat/fuzzysearch
> 
>     * https://github.com/seatgeek/fuzzywuzzy

Thanks for these. Fuzzy searching was something I tried to implement myself a long time ago for certain commands but ultimately I moved past it. I'll be putting some kind of fuzzy search capability for sure to aid in the command's use.

**Comment by Chaussettes99** [comment]
`!map stats` has been rewritten in the latest update (e3f2614c195c7e57f47f1dfc01b54ff9e968c139) to aid in users selecting a specific gamemode automatically when they enter the command. Fuzzy searching will be implemented as soon as I can. I expect it should at least be usable now at least.
